[meta] Add custom range start/end to sai_object_type_t
Workadound for https://github.com/opencomputeproject/SAI/issues/1925

Since SAI_OBJECT_TYPE_EXTENSIONS_MAX is declared as define, compiler
warns about:

error: the result of the conversion is unspecified because .129. is
outside the range of type .sai_object_type_t. {aka
    ._sai_object_type_t.} [-Werror=conversion]

when next value exceeds 7 bits, since that's enough for encode all
values for sai_object_type_t. Unfortunetly #pragma GCC diagnostic
ignored "-Wconversion" is not working (probably gcc bug) then
workaround needs to be addressed in other way.

Those custom ranges can be removed after actual SAI_OBJECT_TYPE_MAX
will reach 128 value